[general]
projectaria_et_path = '/Users/jacksalici/Documents/Thesis/smart-glasses/projectaria_eyetracking/projectaria_eyetracking'


[[aria_recordings]]
vrs = "/Users/jacksalici/Desktop/AriaRecording/test6/e3adbe21-c424-4d3e-b16a-d4af25bd5d4f.vrs"
general_eye_gaze = "/Users/jacksalici/Desktop/AriaRecording/test6/mps_e3adbe21-c424-4d3e-b16a-d4af25bd5d4f_vrs/eye_gaze/general_eye_gaze.csv"

[[aria_recordings]]
#with audio
vrs = "/Users/jacksalici/Desktop/AriaRecording/test8audio/d166d203-762e-434c-a23b-d98cf969e38b.vrs"