[project]
name = "aria_glasses_utils"
version = "0.1.0"
description = "A better tool for managing Aria Project glasses API"

[build-system]
requires = ["setuptools >= 61.0"]
build-backend = "setuptools.build_meta"